// Generated by https://quicktype.io

export interface IProducto {
    isbn:             string;
    title:            string;
    pageCount:        number;
    precio:           string;
    publishedDate:    string;
    thumbnailUrl:     string;
    shortDescription: string;
    longDescription:  string;
    status:           string;
}
